"""
Controlled lip deformation.

Owner: Jayam

Applies intensity-controlled geometric deformation to the lip region
using Thin Plate Spline (TPS) interpolation.

Conceptual flow:
    Original Lip Landmarks
              ↓
    Calculate Displacement Vectors
        (based on volume/intensity)
              ↓
    Displaced Lip Landmarks
              ↓
    Build TPS Transform
        (original → displaced)
              ↓
    Warp Image
              ↓
    Deformed Image

Key principles:
    - Displacement magnitude is controlled by the user's intensity
      parameter, NOT freely generated by AI.
    - Displacement direction follows anatomically plausible directions
      (generally outward from the lip centre for volume increase).
    - The ``upper_lower_balance`` parameter shifts the ratio of
      displacement applied to the upper vs. lower lip.
    - Anchor points at the mouth corners can be fixed (zero
      displacement) to prevent unnatural stretching.

Usage:
    from app.simulations.lips.deformation import apply_lip_deformation
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import numpy as np  # type: ignore[import-untyped]
    from .landmarks import LipLandmarks

logger = logging.getLogger(__name__)


def apply_lip_deformation(
    image: "np.ndarray",
    landmarks: "LipLandmarks",
    *,
    intensity: float = 0.5,
    upper_lower_balance: int = 0,
) -> "np.ndarray":
    """Apply controlled TPS deformation to the lip region.

    Args:
        image: Source image (HxWx3 uint8 BGR).
        landmarks: Lip-specific landmarks in pixel coordinates.
        intensity: Normalised deformation intensity in [0, 1].
                   0.0 = no change, 1.0 = maximum configured displacement.
        upper_lower_balance: -100 to 100.  Negative values shift more
                             displacement to the upper lip; positive
                             values favour the lower lip.

    Returns:
        Deformed image (HxWx3 uint8 BGR, same shape as input).

    TODO:
        - Calculate per-landmark displacement vectors scaled by intensity.
        - Adjust upper/lower ratio using upper_lower_balance.
        - Fix mouth-corner landmarks (zero displacement) as anchors.
        - Build a TPS transform from original → displaced points.
        - Apply the TPS warp to the image.
        - Consider using ``cv2.remap`` or scipy TPS for the warp.
    """
    logger.info(
        "apply_lip_deformation called with intensity=%.2f, balance=%d "
        "(placeholder — returning original image)",
        intensity,
        upper_lower_balance,
    )
    raise NotImplementedError("apply_lip_deformation is not yet implemented.")
